language: java

jdk:
  - oraclejdk8

env:
  - PROFILE=community
  - PROFILE=product

install: true

script:
  - mvn clean install test -D$PROFILE -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
